export const ISLOGIN_REQUEST = 'ISLOGIN_REQUEST'
export const ISLOGIN_SUCCESS = 'ISLOGIN_SUCCESS'
export const ISLOGIN_FAILURE = 'ISLOGIN_FAILURE'

export const USERLOGININ_REQUEST = 'USERLOGININ_REQUEST'
export const USERLOGININ_SUCCESS = 'USERLOGININ_SUCCESS'
export const USERLOGININ_FAILURE = 'USERLOGININ_FAILURE'

export const USERLOGINOUT_REQUEST = 'USERLOGINOUT_REQUEST'
export const USERLOGINOUT_SUCCESS = 'USERLOGINOUT_SUCCESS'
export const USERLOGINOUT_FAILURE = 'USERLOGINOUT_FAILURE'

export const USERBALANCE_REQUEST = 'USERBALANCE_REQUEST'
export const USERBALANCE_SUCCESS = 'USERBALANCE_SUCCESS'
export const USERBALANCE_FAILURE = 'USERBALANCE_FAILURE'

export const PLATFORMNOTICES_REQUEST = 'PLATFORMNOTICES_REQUEST'
export const PLATFORMNOTICES_SUCCESS = 'PLATFORMNOTICES_SUCCESS'
export const PLATFORMNOTICES_FAILURE = 'PLATFORMNOTICES_FAILURE'

export const SYSLOTTERY_REQUEST = 'SYSLOTTERY_REQUEST'
export const SYSLOTTERY_SUCCESS = 'SYSLOTTERY_SUCCESS'
export const SYSLOTTERY_FAILURE = 'SYSLOTTERY_FAILURE'
