export const ISLOGIN_REQUEST = 'ISLOGIN_REQUEST'
export const ISLOGIN_SUCCESS = 'ISLOGIN_SUCCESS'
export const ISLOGIN_FAILURE = 'ISLOGIN_FAILURE'

export const USERLOGININ_REQUEST = 'USERLOGININ_REQUEST'
export const USERLOGININ_SUCCESS = 'USERLOGININ_SUCCESS'
export const USERLOGININ_FAILURE = 'USERLOGININ_FAILURE'